# 1. WHAT IS NUMPY?

## Definition:
NumPy (Numerical Python) is a Python library used for fast numerical and mathematical operations.

## AI/ML Use:
NumPy is used to store and process numerical data such as features, labels, vectors, and matrices.

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40])

print(arr)
print(type(arr))

[10 20 30 40]
<class 'numpy.ndarray'>


## 2. WHY NUMPY?

### Definition:
NumPy is faster and more memory-efficient than Python lists for numerical operations.

### AI/ML Use:
It is widely used for data preprocessing, mathematical calculations, feature engineering, and ML computations.

Example:

In [2]:
import numpy as np

arr = np.array([10, 20, 30])

print(arr * 2)

[20 40 60]


## 3.NUMPY ARRAYS (ndarray)

### Definition:
ndarray is the main data structure in NumPy. It stores multiple values of the same data type.

### AI/ML Use:
Used to represent features, labels, vectors, matrices, images, and numerical datasets.

Example:

In [3]:
import numpy as np

arr = np.array([10, 20, 30])

print(arr)
print(type(arr))

[10 20 30]
<class 'numpy.ndarray'>


## 4.CREATING ARRAYS

### Definition:
NumPy provides different functions to create arrays.

Common functions:
array()
zeros()
ones()
arange()
linspace()

### AI/ML Use:
Used to create datasets, initialize values, and generate numerical data.

Example:

In [4]:
import numpy as np

a = np.array([1, 2, 3])
b = np.zeros(3)
c = np.ones(3)
d = np.arange(1, 5)

print(a)
print(b)
print(c)
print(d)

[1 2 3]
[0. 0. 0.]
[1. 1. 1.]
[1 2 3 4]


## 5.DIMENSIONS

### Definition:
Dimension represents the number of axes in an array.

1D → Vector
2D → Matrix
3D → Tensor

### AI/ML Use:
Different ML and deep learning data require different dimensions.

Example:

In [6]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([[1, 2], [3, 4]])

print(arr1.ndim)
print(arr2.ndim)

1
2


## 6. SHAPE

### Definition:
Shape tells us the number of elements along each dimension.


### Example:
(2, 3) → 2 rows and 3 columns

### AI/ML Use:
Used to understand and verify the structure of datasets before passing them to ML models.

Example:

In [8]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr.shape)

(2, 3)


## 7.SIZE

### Definition:
Size represents the total number of elements in an array.

### AI/ML Use:
Helps verify how many values are present in a dataset or feature matrix.

Example:

## 8.DATA TYPES (dtype)

### Definition:
dtype tells us the data type of elements stored in a NumPy array.

### Common types:
int
float
bool

### AI/ML Use:
Choosing the appropriate data type can reduce memory usage and improve performance.

Example:

In [9]:
import numpy as np

arr = np.array([10, 20, 30])

print(arr.dtype)

int64


## 9.INDEXING

### Definition:
Indexing is used to access individual elements from an array.

### Important:
NumPy uses zero-based indexing.

### AI/ML Use:
Used to access specific rows, columns, features, or values.

Example:

## 10.SLICING

### Definition:
Slicing is used to extract a portion of an array.

### Syntax:
array[start:stop]

### AI/ML Use:
Used to select specific rows, columns, features, or portions of datasets.

Example:

In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

new_arr = arr.reshape(2, 3)

print(new_arr)

[[1 2 3]
 [4 5 6]]


## 11.RESHAPING

### Definition:
Reshaping changes the shape of an array without changing its data.

### AI/ML Use:
Used to convert data into the shape required by ML models.

Example:

In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

new_arr = arr.reshape(2, 3)

print(new_arr)

[[1 2 3]
 [4 5 6]]


## 12.FLATTEN

### Definition:
Flatten converts a multi-dimensional array into a one-dimensional array.

### AI/ML Use:
Useful when converting multi-dimensional data, such as image data, into a 1D feature vector.

Example:

In [12]:
import numpy as np

arr = np.array([[1, 2],
                [3, 4]])

print(arr.flatten())

[1 2 3 4]


## 13. COPY VS VIEW

### Definition:

### Copy:
Creates a completely independent array. Changes to the original do not affect the copy.

### View:
Creates another way to access the same underlying data. Changes can affect the original.

### AI/ML Use:
Important when modifying datasets because accidental changes to the original data can affect model training.

Example:

In [13]:
import numpy as np

arr = np.array([1, 2, 3])

copy_arr = arr.copy()
view_arr = arr.view()

arr[0] = 100

print("Original:", arr)
print("Copy:", copy_arr)
print("View:", view_arr)

Original: [100   2   3]
Copy: [1 2 3]
View: [100   2   3]


## 14.BROADCASTING

### Definition:
Broadcasting allows NumPy to perform operations between arrays of compatible shapes.

### AI/ML Use:
Used heavily in feature scaling, normalization, adding bias, and mathematical operations.

Example:

In [14]:
import numpy as np

arr = np.array([1, 2, 3])

print(arr + 5)

[6 7 8]


## 15.ARRAY OPERATIONS

### Definition:
NumPy allows mathematical operations to be performed directly on arrays.

### Common operations:
Addition
Subtraction
Multiplication
Division

### AI/ML Use:
Used for feature calculations, mathematical transformations, and model computations.

Example:

In [15]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


## 16.UNIVERSAL FUNCTIONS (ufuncs)

### Definition:
ufuncs are NumPy functions that perform fast element-wise operations on arrays.

### Common ufuncs:
np.sqrt()
np.exp()
np.log()
np.add()
np.subtract()
np.multiply()
np.divide()

### AI/ML Use:
Used for fast mathematical transformations and numerical calculations during data preprocessing and ML computations.

Example:

In [16]:
import numpy as np

arr = np.array([1, 4, 9, 16])

print(np.sqrt(arr))
print(np.sum(arr))
print(np.mean(arr))

[1. 2. 3. 4.]
30
7.5
