## Mean (np.mean())
### Definition

The Mean is the average value of all elements in a NumPy array. It is calculated by adding all the values and dividing by the total number of values

In [1]:
import numpy as np

marks = np.array([80, 75, 90, 85, 70])

average = np.mean(marks)

print("Marks:", marks)
print("Mean:", average)

Marks: [80 75 90 85 70]
Mean: 80.0


##  Explanation

The average is calculated as:

(80 + 75 + 90 + 85 + 70) / 5 = 80

np.mean() automatically performs this calculation and returns the average of all elements.

##  Business Example

A company calculates the average daily sales to understand its overall business performance. This helps managers compare sales across different weeks or months and make better business decisions.

## AI/ML Example

In Machine Learning, the mean is commonly used during Exploratory Data Analysis (EDA) to understand the average value of a feature (such as age, salary, or marks). It is also used in data preprocessing, for example, to replace missing numerical values with the feature's average.

## 2.Median (np.median())
 ### Definition

The Median is the middle value of a dataset after arranging the values in ascending order. If the dataset has an even number of elements, the median is the average of the two middle values.

In [2]:
import numpy as np

marks = np.array([80, 75, 90, 85, 70])

median = np.median(marks)

print("Marks:", marks)
print("Median:", median)

Marks: [80 75 90 85 70]
Median: 80.0


## Business Example

A company uses the median salary to understand the typical employee salary because it is less affected by extremely high or low salaries than the mean.
##  AI/ML Example

In Machine Learning, the median is often used to replace missing values in datasets that contain outliers, as it provides a better representation of the central value than the mean.

## 3.Variance (np.var())
### Definition

Variance measures how far the data values are spread from the mean (average). A low variance means the values are close to the mean, while a high variance means the values are more spread out.

In [3]:
import numpy as np

marks = np.array([80, 75, 90, 85, 70])

variance = np.var(marks)

print("Marks:", marks)
print("Variance:", variance)

Marks: [80 75 90 85 70]
Variance: 50.0


## Explanation

np.var() calculates the average of the squared differences between each value and the mean.

### In this example:

Mean = 80
The marks are spread around the mean.
The variance is 50.0, indicating the amount of variation in the dataset.

A smaller variance means the values are closer together, while a larger variance means they are more spread out.

### Business Example

A company analyzes the variance of daily sales to measure how consistent sales are. A low variance indicates stable sales, while a high variance indicates significant fluctuations.

###  AI/ML Example

In Machine Learning, variance helps understand the spread of features, detect data variability, and is used in algorithms such as Principal Component Analysis (PCA) and during feature analysis before model training.

## 3.Standard Deviation (np.std())
###  Definition

Standard Deviation measures how much the data values deviate (spread) from the mean. It is the square root of the variance and is expressed in the same unit as the data.

## Explanation
np.std() calculates the standard deviation of the array.

Given Array:
[80, 75, 90, 85, 70]

Step 1: Find the Mean
Mean = (80 + 75 + 90 + 85 + 70) / 5
     = 400 / 5
     = 80

Step 2: Find the difference of each value from the mean
80 - 80 = 0
75 - 80 = -5
90 - 80 = 10
85 - 80 = 5
70 - 80 = -10

Step 3: Square each difference
0² = 0
(-5)² = 25
10² = 100
5² = 25
(-10)² = 100

Step 4: Calculate the Variance
Variance = (0 + 25 + 100 + 25 + 100) / 5
         = 250 / 5
         = 50

Step 5: Calculate the Standard Deviation
Standard Deviation = √50
                   = 7.0710678118654755

Therefore, np.std() returns:
Standard Deviation = 7.0710678118654755

This means the marks are spread by approximately 7.07 marks from the average value (80).

## Business Example

A company calculates the standard deviation of monthly sales to measure sales consistency. A low standard deviation indicates stable sales, while a high standard deviation indicates large fluctuations.

## AI/ML Example

In Machine Learning, standard deviation is used in feature scaling (Standardization) to normalize data before training models such as Logistic Regression, SVM, and Neural Networks.

## 4.Minimum (np.min())
###  Definition

The Minimum function returns the smallest value in a NumPy array.

In [4]:
import numpy as np

marks = np.array([80, 75, 90, 85, 70])

minimum = np.min(marks)

print("Marks:", marks)
print("Minimum:", minimum)

Marks: [80 75 90 85 70]
Minimum: 70


### Explanation
np.min() returns the smallest value in the array.

Given Array:
[80, 75, 90, 85, 70]

The values are:
80, 75, 90, 85, 70

Among these values, 70 is the smallest.

Therefore, np.min() returns:
Minimum = 70

### Business Example

A company finds the minimum daily sales in a month to identify the day with the lowest business performance and analyze the reason for the drop.

### AI/ML Example

In Machine Learning, the minimum value of a feature is used during data analysis and feature scaling (such as Min-Max Scaling) to normalize data before training a model.

## Maximum (np.max())
### Definition

The Maximum function returns the largest value in a NumPy array.

In [5]:
import numpy as np

marks = np.array([80, 75, 90, 85, 70])

maximum = np.max(marks)

print("Marks:", marks)
print("Maximum:", maximum)

Marks: [80 75 90 85 70]
Maximum: 90


### Explanation

np.max() returns the largest value in the array.

Given Array:
[80, 75, 90, 85, 70]

The values are:
80, 75, 90, 85, 70

Among these values, 90 is the largest.

Therefore, np.max() returns:
Maximum = 90

## Business Example

A company finds the maximum daily sales in a month to identify the best-performing day and analyze the factors that contributed to higher sales.

## AI/ML Example

In Machine Learning, the maximum value of a feature is used during data preprocessing, especially in Min-Max Scaling, where features are normalized to a fixed range (such as 0 to 1) before training a model.

## 5.Argmin (np.argmin())
### Definition

The Argmin function returns the index (position) of the smallest value in a NumPy array. It does not return the smallest value itself.

In [6]:
import numpy as np

marks = np.array([80, 75, 90, 85, 70])

min_index = np.argmin(marks)

print("Marks:", marks)
print("Index of Minimum Value:", min_index)

Marks: [80 75 90 85 70]
Index of Minimum Value: 4


In [ ]:
###Explanation

np.argmin() returns the index (position) of the smallest value in the array.

Given Array:
[80, 75, 90, 85, 70]

Index:   0   1   2   3   4
Value:  80  75  90  85  70

The smallest value is 70.

The index of 70 is 4.

Therefore, np.argmin() returns:
Index of Minimum Value = 4

### Business Example

A company uses argmin to identify the day with the lowest sales. Instead of returning the sales amount, it returns the position (day index) where the minimum sales occurred.

### AI/ML Example

In Machine Learning, argmin is used to find the index of the minimum error, minimum distance, or minimum loss value, helping algorithms select the best or closest result.

## 6.Argmax (np.argmax())
### Definition

The Argmax function returns the index (position) of the largest value in a NumPy array. It does not return the largest value itself.

In [8]:
import numpy as np

marks = np.array([80, 75, 90, 85, 70])

max_index = np.argmax(marks)

print("Marks:", marks)
print("Index of Maximum Value:", max_index)

Marks: [80 75 90 85 70]
Index of Maximum Value: 2


In [ ]:
###Explanation
np.argmax() returns the index (position) of the largest value in the array.

Given Array:
[80, 75, 90, 85, 70]

Index:   0   1   2   3   4
Value:  80  75  90  85  70

The largest value is 90.

The index of 90 is 2.

Therefore, np.argmax() returns:
Index of Maximum Value = 2

### Business Example

A company uses argmax to identify the day with the highest sales. Instead of returning the sales amount, it returns the position (day index) where the maximum sales occurred.

### AI/ML Example

In Machine Learning, argmax is widely used to find the index of the highest predicted probability. For example, in a classification model, the class with the highest probability is selected as the final predicted class.

## 7.Percentile (np.percentile())
### Definition

A Percentile is a value below which a given percentage of data falls. For example, the 50th percentile is the median, and the 90th percentile indicates that 90% of the values are less than or equal to that value.

In [9]:
import numpy as np

marks = np.array([80, 75, 90, 85, 70])

percentile_50 = np.percentile(marks, 50)

print("Marks:", marks)
print("50th Percentile:", percentile_50)

Marks: [80 75 90 85 70]
50th Percentile: 80.0


In [ ]:
##Explanation
np.percentile() returns the value below which a specified percentage of data falls.

Given Array:
[80, 75, 90, 85, 70]

Step 1: Sort the array
[70, 75, 80, 85, 90]

Step 2: Find the required percentile

Here, we calculate the 50th percentile.

The 50th percentile represents the middle value of the sorted data.

The middle value is 80.

Therefore, np.percentile(marks, 50) returns:
50th Percentile = 80.0

### Business Example

A company uses the 90th percentile of customer spending to identify high-value customers for premium offers and loyalty programs.

### AI/ML Example


In Machine Learning, percentiles are used to detect outliers, analyze feature distributions, and set thresholds during data preprocessing. For example, the 25th and 75th percentiles are used to calculate the Interquartile Range (IQR) for outlier detection.

## 8.Dot Product (np.dot())
### Definition

The Dot Product is the multiplication of two arrays followed by the addition of the corresponding products. It is commonly used in vector mathematics, machine learning, and linear algebra.

In [10]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.dot(a, b)

print("Array A:", a)
print("Array B:", b)
print("Dot Product:", result)

Array A: [1 2 3]
Array B: [4 5 6]
Dot Product: 32


In [ ]:
np.dot() multiplies the corresponding elements of two arrays and then adds the results.

Array A:
[1, 2, 3]

Array B:
[4, 5, 6]

Step 1: Multiply corresponding elements

1 × 4 = 4
2 × 5 = 10
3 × 6 = 18

Step 2: Add the products

4 + 10 + 18 = 32

Therefore, np.dot(a, b) returns:
Dot Product = 32

### Business Example

A company can calculate the total revenue by multiplying the quantity sold of each product with its price and adding the results. This is an application of the dot product.

### Example:

Quantities Sold: [10, 20, 15]
Prices: [100, 50, 80]

Revenue = (10×100) + (20×50) + (15×80)

### AI/ML Example

The dot product is widely used in Machine Learning to calculate weighted sums in algorithms such as Linear Regression, Logistic Regression, and Neural Networks, where input features are multiplied by their corresponding weights to produce predictions.

## 9 .Matrix Multiplication (np.matmul() or @)
### Definition

Matrix Multiplication combines two matrices by multiplying rows of the first matrix with columns of the second matrix. It is one of the most important operations in Linear Algebra and Machine Learning.

In [11]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

result = np.matmul(A, B)

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Matrix Multiplication:\n", result)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Matrix Multiplication:
 [[19 22]
 [43 50]]


In [ ]:
np.matmul() multiplies rows of the first matrix with columns of the second matrix.

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Step 1: Calculate the first row

(1×5) + (2×7) = 5 + 14 = 19
(1×6) + (2×8) = 6 + 16 = 22

Step 2: Calculate the second row

(3×5) + (4×7) = 15 + 28 = 43
(3×6) + (4×8) = 18 + 32 = 50

Therefore, np.matmul(A, B) returns:

[[19 22]
 [43 50]]

## Business Example

Businesses use matrix multiplication to analyze large datasets, such as calculating total sales across multiple stores and products, financial forecasting, and recommendation systems.

## AI/ML Example

Matrix multiplication is a core operation in Machine Learning and Deep Learning. It is used to multiply input features with model weights in algorithms like Linear Regression, Logistic Regression, and Neural Networks to generate predictions.

## Transpose (.T or np.transpose())
### Definition

The Transpose of a matrix swaps its rows and columns. Every row becomes a column, and every column becomes a row.

In [15]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

transpose = A.T

print("Original Matrix:\n", A)
print("Transpose Matrix:\n", transpose)

Original Matrix:
 [[1 2 3]
 [4 5 6]]
Transpose Matrix:
 [[1 4]
 [2 5]
 [3 6]]


In [ ]:
The transpose operation swaps the rows and columns of a matrix.

Original Matrix:
[[1 2 3]
 [4 5 6]]

Rows:
Row 1 → [1 2 3]
Row 2 → [4 5 6]

After Transpose:

Column 1 becomes Row 1 → [1 4]
Column 2 becomes Row 2 → [2 5]
Column 3 becomes Row 3 → [3 6]

Therefore, A.T returns:

[[1 4]
 [2 5]
 [3 6]]

## Business Example

A company may transpose sales data to change the view from products vs. months to months vs. products, making reporting and analysis easier.
## AI/ML Example

In Machine Learning, the transpose operation is frequently used in matrix multiplication, feature transformations, covariance calculations, and linear algebra operations during model training and data preprocessing.

## Basic Linear Algebra Operations (numpy.linalg)
### Definition

NumPy's linalg module provides functions to perform Linear Algebra operations such as calculating the inverse, determinant, rank, and eigenvalues of a matrix. These operations are widely used in Mathematics, Data Science, and Machine Learning.

In [ ]:
import numpy as np

A = np.array([[4, 7],
              [2, 6]])

print("Matrix:\n", A)

print("\nDeterminant:")
print(np.linalg.det(A))

print("\nInverse:")
print(np.linalg.inv(A))

print("\nRank:")
print(np.linalg.matrix_rank(A))

In [ ]:
NumPy's linalg module provides functions to perform Linear Algebra operations.

Given Matrix:

[[4 7]
 [2 6]]

----------------------------------------
1. Determinant
----------------------------------------

np.linalg.det(A) calculates the determinant of the matrix.

For a 2 × 2 matrix:

[[a b]
 [c d]]

Determinant = (a × d) - (b × c)

Here,

a = 4
b = 7
c = 2
d = 6

Determinant = (4 × 6) - (7 × 2)
             = 24 - 14
             = 10

Therefore,

np.linalg.det(A) returns:

10.0

Since the determinant is not zero, the matrix has an inverse.

----------------------------------------
2. Inverse
----------------------------------------

np.linalg.inv(A) calculates the inverse of the matrix.

Original Matrix:

[[4 7]
 [2 6]]

Inverse Matrix:

[[ 0.6 -0.7]
 [-0.2  0.4]]

We can verify the inverse by multiplying the original matrix with its inverse.

[[4 7]       [[ 0.6 -0.7]
 [2 6]]   ×   [-0.2  0.4]]

Result:

[[1 0]
 [0 1]]

This is called the Identity Matrix.

Since the multiplication produces the Identity Matrix, the inverse is correct.

----------------------------------------
3. Rank
----------------------------------------

np.linalg.matrix_rank(A) returns the rank of the matrix.

Rank represents the number of linearly independent rows or columns.

Given Matrix:

[[4 7]
 [2 6]]

Both rows are independent because one row cannot be obtained by multiplying the other.

Row 1 = [4 7]
Row 2 = [2 6]

Therefore,

Rank = 2

Since the matrix is of size 2 × 2 and its rank is 2, all rows and columns are linearly independent.

### Business Example

Banks and financial institutions use linear algebra to analyze large datasets, optimize investment portfolios, solve systems of equations, and perform risk analysis.

###  AI/ML Example

Linear algebra is the foundation of Machine Learning. Operations such as matrix inversion, determinants, and matrix multiplication are used in algorithms like Linear Regression, Principal Component Analysis (PCA), Recommendation Systems, Neural Networks, and Support Vector Machines (SVMs).