## 1.Random Numbers (np.random.rand())
### Definition

np.random.rand() generates random floating-point numbers between 0 (inclusive) and 1 (exclusive). It can create a single random number or an array of random numbers.

In [7]:
import numpy as np

random_numbers = np.random.rand(5)

print("Random Numbers:", random_numbers)

Random Numbers: [0.32695007 0.87201911 0.15513263 0.15624906 0.60970206]


In [ ]:
np.random.rand(5) generates 5 random floating-point numbers.

The values are:
0.54
0.18
0.91
0.33
0.76

Each value is:
• Greater than or equal to 0
• Less than 1

Since these numbers are generated randomly, they will be different every time you run the program.

The number 5 specifies how many random values should be generated.

### Business Example

An online shopping company generates random customer samples to test a new website design before launching it to all users.

### AI/ML Example

In Machine Learning, random numbers are used to initialize model weights, generate sample data, split datasets, and simulate experiments during model development.

## 2.Random Seed (np.random.seed())
### Definition

np.random.seed() sets a fixed starting point for the random number generator. Using the same seed value produces the same random numbers every time the program is executed, making the results reproducible.

In [8]:
import numpy as np

np.random.seed(10)

random_numbers = np.random.rand(5)

print("Random Numbers:", random_numbers)

Random Numbers: [0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]


In [ ]:
np.random.seed(10) initializes the random number generator with the value 10.

Step 1:
The seed value is set to 10.

Step 2:
np.random.rand(5) generates 5 random numbers.

Since the seed is fixed, NumPy starts generating numbers from the same starting point every time.

Therefore, the output will always be:

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]

If you change the seed value (for example, 20 or 100), a different sequence of random numbers will be generated.

If you do not use np.random.seed(), the output will be different every time you run the program.

### Business Example

A company testing a new pricing strategy uses a fixed random seed so every team member gets the same sample data, making the results consistent and easy to compare.

### AI/ML Example

In Machine Learning, np.random.seed() is used to ensure reproducible results. It guarantees that data splitting, model initialization, and experiments produce the same output every time the code is executed, making debugging and model comparison easier.

## 3.Random Integers (np.random.randint())
### Definition

np.random.randint() generates random integer values within a specified range. You can generate a single integer or multiple integers.

In [2]:
import numpy as np

random_numbers = np.random.randint(1, 10, size=5)

print("Random Integers:", random_numbers)

Random Integers: [9 2 5 2 4]


In [ ]:
np.random.randint(1, 10, size=5) generates 5 random integers.

Here,

1  -> Starting value (inclusive)
10 -> Ending value (exclusive)
size=5 -> Generate 5 random integers

Possible values are:
1, 2, 3, 4, 5, 6, 7, 8, 9

In this example, NumPy generated:

[3 8 1 5 7]

Every time you run the program, different random integers may be generated unless you use np.random.seed().

### Business Example

A company randomly selects 5 customer IDs from a range of IDs to conduct a customer satisfaction survey.
### AI/ML Example

In Machine Learning, np.random.randint() is commonly used to generate sample datasets, create random class labels, and simulate data for testing algorithms before using real-world datasets.

## 4.Random Choice (np.random.choice())
### Definition

np.random.choice() randomly selects one or more values from a given array or list. It can select values with replacement (default) or without replacement.

In [5]:
import numpy as np

fruits = ["Apple", "Banana", "Orange", "Mango"]

selected = np.random.choice(fruits, size=2)

print("Selected Fruits:", selected)

Selected Fruits: ['Apple' 'Mango']


In [ ]:
np.random.choice() randomly selects values from the given array.

Given Array:

['Apple', 'Banana', 'Orange', 'Mango']

Here,

size=2

means two values should be selected.

In this example, NumPy selected:

['Orange' 'Apple']

Since the selection is random, the output may change every time you run the program.

By default, np.random.choice() selects values with replacement, which means the same value can be selected more than once.

### Business Example

An e-commerce company randomly selects 100 customers from its customer database to participate in a feedback survey.

### AI/ML Example

In Machine Learning, np.random.choice() is used to randomly sample data points, create training and testing samples, and perform bootstrapping techniques used in ensemble learning algorithms like Random Forest.

## 5.Shuffle (np.random.shuffle())
### Definition

np.random.shuffle() randomly rearranges (shuffles) the elements of an existing array. It modifies the original array directly.

In [6]:
import numpy as np

numbers = np.array([1, 2, 3, 4, 5])

np.random.shuffle(numbers)

print("Shuffled Array:", numbers)

Shuffled Array: [4 1 5 2 3]


In [ ]:
np.random.shuffle() randomly rearranges the elements of the original array.

Original Array:

[1 2 3 4 5]

After shuffling, one possible output is:

[3 5 1 4 2]

Notice that:

• The values remain the same.
• Only their positions change.
• The original array is modified directly.

Every time you run the program, a different arrangement may be produced unless you use np.random.seed().

### Business Example

A company shuffles a list of interview candidates before assigning interview slots to ensure the order is random and unbiased.

### AI/ML Example

In Machine Learning, np.random.shuffle() is used to shuffle datasets before training a model. This helps prevent bias caused by the original order of the data and improves model generalization.

## 6.Permutation (np.random.permutation())
### Definition

np.random.permutation() returns a new shuffled array without modifying the original array. Unlike np.random.shuffle(), it creates a copy and leaves the original array unchanged.

In [7]:
import numpy as np

numbers = np.array([1, 2, 3, 4, 5])

permuted = np.random.permutation(numbers)

print("Original Array:", numbers)
print("Permuted Array:", permuted)

Original Array: [1 2 3 4 5]
Permuted Array: [3 4 2 5 1]


In [ ]:
np.random.permutation() creates a new shuffled array.

Original Array:

[1 2 3 4 5]

After permutation, one possible output is:

[4 1 5 2 3]

Notice that:

• The original array remains unchanged.
• A new shuffled array is returned.
• The values remain the same.
• Only their positions are changed.

Every time you run the program, a different permutation may be generated unless you use np.random.seed().

### Business Example

A company creates a random order of customer IDs for marketing campaigns while keeping the original customer database unchanged.

### AI/ML Example

In Machine Learning, np.random.permutation() is commonly used to randomize dataset indices before splitting data into training and testing sets, while preserving the original dataset.

## 7.Random Distributions (np.random.normal(), np.random.uniform(), np.random.binomial())
### Definition

Random distributions generate random numbers that follow a specific statistical distribution. Different distributions are used depending on the type of data being modeled.

#### Common distributions in NumPy include:

* np.random.normal() → Normal (Gaussian) Distribution
* np.random.uniform() → Uniform Distribution
* np.random.binomial() → Binomial Distribution

In [8]:
import numpy as np

normal = np.random.normal(loc=50, scale=10, size=5)
uniform = np.random.uniform(low=10, high=20, size=5)
binomial = np.random.binomial(n=10, p=0.5, size=5)

print("Normal Distribution:", normal)
print("Uniform Distribution:", uniform)
print("Binomial Distribution:", binomial)

Normal Distribution: [60.08980816 50.22516901 63.43815971 65.87834257 39.13918122]
Uniform Distribution: [15.27578787 13.56558665 11.26798347 11.28433744 19.10355009]
Binomial Distribution: [6 4 9 4 5]


In [ ]:
1. Normal Distribution

np.random.normal(loc=50, scale=10, size=5)

loc=50   -> Mean (average) of the distribution
scale=10 -> Standard deviation
size=5   -> Generate 5 random values

The generated values are centered around 50.

----------------------------------------

2. Uniform Distribution

np.random.uniform(low=10, high=20, size=5)

low=10   -> Minimum value (inclusive)
high=20  -> Maximum value (exclusive)
size=5   -> Generate 5 random values

The generated values are evenly distributed between 10 and 20.

----------------------------------------

3. Binomial Distribution

np.random.binomial(n=10, p=0.5, size=5)
 
n=10   -> Number of trials
p=0.5  -> Probability of success
size=5 -> Generate 5 values

Each generated value represents the number of successful outcomes in 10 trials.

Since all three functions generate random values, the output changes every time the program runs unless np.random.seed() is used.

###  Business Example

Businesses use random distributions to simulate real-world scenarios such as customer demand, product sales, waiting times, inventory planning, and financial risk analysis.

* Normal Distribution: Employee salaries or product weights.
* Uniform Distribution: Random discount percentages or coupon values.
* Binomial Distribution: Number of customers who purchase a product out of a fixed number of visitors.
### AI/ML Example

Random distributions are widely used in Machine Learning to generate synthetic datasets, initialize model parameters, perform simulations, and test algorithms. For example, normal distributions are often used for initializing neural network weights, while binomial distributions are used to simulate binary outcomes.